title: Collections
updated_by: c140131f-c375-40c2-b2b1-b1e0303f6b45
updated_at: 1738492063
blueprint: guides
guide_category_desc:
  -
    type: paragraph
    content:
      -
        type: text
        text: "You can think of a collection as a grouping mechanism—for instance, it might represent products, pages, services, or any other type of content. Essentially, every time you add new content within a collection, you're creating an "
      -
        type: text
        marks:
          -
            type: bold
        text: entry
      -
        type: text
        text: .
