title: General
updated_by: c140131f-c375-40c2-b2b1-b1e0303f6b45
updated_at: 1738491914
blueprint: guides
guide_category_desc:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'The perfect starting point for learning Statamic. With bite-sized videos, you’ll quickly get familiar with your new Content Management System (CMS).'
