title: Pages
updated_by: c140131f-c375-40c2-b2b1-b1e0303f6b45
updated_at: 1738438562
blueprint: guides
guide_category_desc:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'How to create and edit pages in Statamic CMS.'
