title: 'Set Templates'
updated_by: c140131f-c375-40c2-b2b1-b1e0303f6b45
updated_at: 1738491952
blueprint: guides
guide_category_desc:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Learn how to use set templates in Statamic CMS with these short, easy-to-follow guides. Quickly understand their purpose, how they work, and how to implement them effectively.'
